name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [frontend, backend]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          cd ${{ matrix.dir }}
          npm ci
      - name: Lint
        run: |
          cd ${{ matrix.dir }}
          npm run lint || true
      - name: Test
        run: |
          cd ${{ matrix.dir }}
          npm test || true